# Project information
site_name: "VertDocs"
theme_dir: 'vdmaterial/material'
site_description: 'Vertcoin Documentation'
site_url: 'http://docs.vertcoin.org'
site_favicon: 'images/favicon.png'

pages:
    - Home: index.md
    - Getting Started: Getting-Started.md
    - Wallets:     
        - Core Wallet: Wallets/Core-Wallet.md
        - Electrum Wallet: Wallets/Electrum.md

extra_css:
  - 'stylesheets/extra.css'
  
extra:  
    
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/vertcoin'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/vertcoin/'
    - type: 'slack'
      link: 'https://slack.vtconline.org/'
    - type: 'facebook'
      link: 'https://linkedin.com/in/squidfunk'
      
   
copyright: 'Copyright &copy; 2017 Vertcoin'


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  
  
