# Project information
site_name: "VertDocs"
theme_dir: 'vdmaterial/material'
site_description: 'Vertcoin Documentation'
site_url: 'http://docs.vertcoin.org'

extra_css:
  - 'stylesheets/extra.css'
  
extra:
  palette:
    accent: 'green'
    
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/squidfunk'
      
   
copyright: 'Copyright &copy; 2016 - 2017 John Doe'


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  